/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;
import bean.JbsUsuario;
import dao.UsuarioDAO;

/**
 *
 * @author Janaína B da Silva
 */
public class JDlgUsuario extends javax.swing.JDialog {

    private boolean incluindo;
    MaskFormatter mascaraCpf;
    MaskFormatter mascaraData;
    /**
     * Creates new form JDlgUsuario
     */
    public JDlgUsuario(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
        initComponents();
        Util.habilitar(false,JBS_jTxtCodigo, JBS_jTxtNome, JBS_jTxtApelido, JBS_jFmtCpf, JBS_jFmtDataNascimento, JBS_jPwfSenha,
            JBS_jCboNivel, JBS_jChbAtivo, JBS_jBtnCancelar, JBS_jBtnConfirmar);
        Util.habilitar(true, JBS_jBtnIncluir, JBS_jBtnAlterar, JBS_jBtnExcluir, JBS_jBtnPesquisar);
        setTitle("Cadastro de Usuarios");
        setLocationRelativeTo(null);
        try {
            mascaraCpf = new MaskFormatter("###.###.###-##");
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        JBS_jFmtCpf.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
        JBS_jFmtDataNascimento.setFormatterFactory(new DefaultFormatterFactory(mascaraData));
    }

    public JbsUsuario ViewBean(){
        JbsUsuario jbsUsuario = new JbsUsuario();
        int id = Integer.valueOf(JBS_jTxtCodigo.getText());
        jbsUsuario.setJbsIdUsuario(id);
        jbsUsuario.setJbsNome(JBS_jTxtNome.getText());
        jbsUsuario.setJbsApelido(JBS_jTxtApelido.getText());
        jbsUsuario.setJbsCpf(JBS_jFmtCpf.getText());
        jbsUsuario.setJbsSenha(JBS_jPwfSenha.getText());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            jbsUsuario.setJbsDataNasc(formato.parse(JBS_jFmtDataNascimento.getText()));
        } catch (ParseException ex) {
            //Logger.getLogger(JDlgVendas.class.getName()).log(Level.SEVERE, null, ex);
            System.out.print("por favor funciona: " + ex.getMessage());
        }
        jbsUsuario.setJbsNivel(JBS_jCboNivel.getSelectedIndex());
        if(JBS_jChbAtivo.isSelected()==true){
        jbsUsuario.setJbsAtivo("S");
        } else {
        jbsUsuario.setJbsAtivo("N");
        }
        return jbsUsuario;
    }
    
    public void beanView(JbsUsuario jbsUsuario){
        String valor = String.valueOf(jbsUsuario.getJbsIdUsuario());
        JBS_jTxtCodigo.setText(valor);
        JBS_jTxtNome.setText(jbsUsuario.getJbsNome());
        JBS_jTxtApelido.setText(jbsUsuario.getJbsApelido());
        JBS_jFmtCpf.setText(jbsUsuario.getJbsCpf());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
//        String dataStr = formato.format();
        JBS_jFmtDataNascimento.setText(formato.format(jbsUsuario.getJbsDataNasc()));
        JBS_jPwfSenha.setText(jbsUsuario.getJbsSenha());
        JBS_jCboNivel.setSelectedIndex(jbsUsuario.getJbsNivel());
        if(jbsUsuario.getJbsAtivo().equals("S") == true){
            JBS_jChbAtivo.setSelected(true);
        } else {
            JBS_jChbAtivo.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBS_jTxtNome = new javax.swing.JTextField();
        JBS_jChbAtivo = new javax.swing.JCheckBox();
        JBS_jTxtApelido = new javax.swing.JTextField();
        JBS_jBtnIncluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JBS_jBtnAlterar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JBS_jBtnExcluir = new javax.swing.JButton();
        JBS_jFmtCpf = new javax.swing.JFormattedTextField();
        JBS_jBtnConfirmar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JBS_jBtnPesquisar = new javax.swing.JButton();
        JBS_jFmtDataNascimento = new javax.swing.JFormattedTextField();
        JBS_jBtnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JBS_jTxtCodigo = new javax.swing.JTextField();
        JBS_jPwfSenha = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JBS_jCboNivel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JBS_jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jTxtNomeActionPerformed(evt);
            }
        });

        JBS_jChbAtivo.setText("Ativo");

        JBS_jTxtApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jTxtApelidoActionPerformed(evt);
            }
        });

        JBS_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        JBS_jBtnIncluir.setText("Incluir");
        JBS_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jBtnIncluirActionPerformed(evt);
            }
        });

        jLabel3.setText("Apelido");

        JBS_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        JBS_jBtnAlterar.setText("Alterar");
        JBS_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jBtnAlterarActionPerformed(evt);
            }
        });

        jLabel4.setText("CPf");

        JBS_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        JBS_jBtnExcluir.setText("Excluir");
        JBS_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jBtnExcluirActionPerformed(evt);
            }
        });

        JBS_jFmtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jFmtCpfActionPerformed(evt);
            }
        });

        JBS_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        JBS_jBtnConfirmar.setText("Confirmar");
        JBS_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jBtnConfirmarActionPerformed(evt);
            }
        });

        jLabel5.setText("Data de Nascimento");

        JBS_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        JBS_jBtnPesquisar.setText("Pesquisar");
        JBS_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jBtnPesquisarActionPerformed(evt);
            }
        });

        JBS_jFmtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jFmtDataNascimentoActionPerformed(evt);
            }
        });

        JBS_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        JBS_jBtnCancelar.setText("Cancelar");
        JBS_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jBtnCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Senha");

        JBS_jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jTxtCodigoActionPerformed(evt);
            }
        });

        jLabel8.setText("Codigo");

        jLabel7.setText("Nivel");

        jLabel2.setText("Nome");

        JBS_jCboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "fornecedor", "usuario" }));
        JBS_jCboNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jCboNivelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBS_jTxtNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBS_jTxtApelido)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBS_jBtnIncluir)
                                .addGap(18, 18, 18)
                                .addComponent(JBS_jBtnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBS_jBtnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBS_jBtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBS_jBtnConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBS_jBtnPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBS_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(JBS_jFmtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBS_jPwfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBS_jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBS_jChbAtivo))
                            .addComponent(jLabel8)
                            .addComponent(JBS_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(138, 138, 138)
                                .addComponent(jLabel7)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBS_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBS_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBS_jTxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBS_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBS_jFmtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBS_jPwfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBS_jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBS_jChbAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBS_jBtnIncluir)
                    .addComponent(JBS_jBtnAlterar)
                    .addComponent(JBS_jBtnExcluir)
                    .addComponent(JBS_jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBS_jBtnPesquisar)
                    .addComponent(JBS_jBtnCancelar))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBS_jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBS_jTxtNomeActionPerformed

    private void JBS_jTxtApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jTxtApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBS_jTxtApelidoActionPerformed

    private void JBS_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jBtnIncluirActionPerformed
        Util.habilitar(true,JBS_jTxtCodigo, JBS_jTxtNome, JBS_jTxtApelido, JBS_jFmtCpf, JBS_jFmtDataNascimento, JBS_jPwfSenha,
            JBS_jCboNivel, JBS_jChbAtivo, JBS_jBtnCancelar, JBS_jBtnConfirmar);
        Util.habilitar(false, JBS_jBtnIncluir, JBS_jBtnAlterar, JBS_jBtnExcluir, JBS_jBtnPesquisar);
        Util.limparCampos(JBS_jTxtCodigo, JBS_jTxtNome, JBS_jTxtApelido, JBS_jFmtCpf, JBS_jFmtDataNascimento, JBS_jPwfSenha,
            JBS_jCboNivel, JBS_jChbAtivo);
        incluindo = true;
        //Double.parseDouble(String string);
    }//GEN-LAST:event_JBS_jBtnIncluirActionPerformed

    private void JBS_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jBtnAlterarActionPerformed

        Util.habilitar(true,JBS_jTxtCodigo, JBS_jTxtNome, JBS_jTxtApelido, JBS_jFmtCpf, JBS_jFmtDataNascimento, JBS_jPwfSenha,
            JBS_jCboNivel, JBS_jChbAtivo, JBS_jBtnCancelar, JBS_jBtnConfirmar);
        Util.habilitar(false, JBS_jBtnIncluir, JBS_jBtnAlterar, JBS_jBtnExcluir, JBS_jBtnPesquisar);
        incluindo = false;
    }//GEN-LAST:event_JBS_jBtnAlterarActionPerformed

    private void JBS_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        //        Util.habilitar(true,jTxtCodigo, jTxtNome, jTxtApelido, jFmtCpf, jFmtDataNascimento, jPwfSenha,
            //                jCboNivel, jChbAtivo, jBtnCancelar, jBtnConfirmar);
        //        Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        //        if (Util.perguntar("Excluiu essa bagaça")== true) {
            //            Usuario usuario = ViewBean();
            //            Usuario_DAO usuario_DAO = new Usuario_DAO();
            //            usuario_DAO.delete(usuario);
            //
            //        } else {
            //        Util.mensagem("Exclusão cancelada");
            //        }
        //        limparCampos();

        if (Util.perguntar("Deseja excluir o registro?") == true){

        }else{
            Util.mensagem("Exclusão cancelada");
        }
        Util.limparCampos(JBS_jTxtCodigo, JBS_jTxtNome, JBS_jTxtApelido, JBS_jFmtCpf, JBS_jFmtDataNascimento, JBS_jPwfSenha,
            JBS_jCboNivel, JBS_jChbAtivo);
    }//GEN-LAST:event_JBS_jBtnExcluirActionPerformed

    private void JBS_jFmtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jFmtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBS_jFmtCpfActionPerformed

    private void JBS_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jBtnConfirmarActionPerformed
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        if(incluindo == true){
            usuarioDAO.insert(ViewBean());//bean com bean retorna bean
        } else {
            usuarioDAO.update(ViewBean());
        }
        Util.habilitar(false,JBS_jTxtCodigo, JBS_jTxtNome, JBS_jTxtApelido, JBS_jFmtCpf, JBS_jFmtDataNascimento, JBS_jPwfSenha,
            JBS_jCboNivel, JBS_jChbAtivo, JBS_jBtnCancelar, JBS_jBtnConfirmar);
        Util.habilitar(true, JBS_jBtnIncluir, JBS_jBtnAlterar, JBS_jBtnExcluir, JBS_jBtnPesquisar);
        Util.limparCampos(JBS_jTxtCodigo, JBS_jTxtNome, JBS_jTxtApelido, JBS_jFmtCpf, JBS_jFmtDataNascimento, JBS_jPwfSenha,
            JBS_jCboNivel, JBS_jChbAtivo);
    }//GEN-LAST:event_JBS_jBtnConfirmarActionPerformed

    private void JBS_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        //habilitar();
        //        String pesquisar = JOptionPane.showInputDialog(null, "Entre com o código (FK)");
        //        Usuario_DAO usuario_DAO = new Usuario_DAO();
        //        int id = Integer.valueOf(pesquisar);
        //        Usuario usuario = (Usuario) usuario_DAO.list(id); //list retorna o bean e ttansforma o bean em objeto
        //        beanView(usuario);
        //        ALterarExcluir();
        //
        JDlgUsuariosPesquisa jDlgUsuariosPesquisa = new JDlgUsuariosPesquisa(null, true);
        jDlgUsuariosPesquisa.setTelaAnterior(this);
        jDlgUsuariosPesquisa.setVisible(true);

        JBS_jBtnAlterar.setEnabled(true);
        JBS_jBtnPesquisar.setEnabled(true);
        JBS_jBtnCancelar.setEnabled(true);
        JBS_jBtnConfirmar.setEnabled(false);
        JBS_jBtnExcluir.setEnabled(true);
    }//GEN-LAST:event_JBS_jBtnPesquisarActionPerformed

    private void JBS_jFmtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jFmtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBS_jFmtDataNascimentoActionPerformed

    private void JBS_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jBtnCancelarActionPerformed

        Util.habilitar(false,JBS_jTxtCodigo, JBS_jTxtNome, JBS_jTxtApelido, JBS_jFmtCpf, JBS_jFmtDataNascimento, JBS_jPwfSenha,
            JBS_jCboNivel, JBS_jChbAtivo, JBS_jBtnCancelar, JBS_jBtnConfirmar);
        Util.habilitar(true, JBS_jBtnIncluir, JBS_jBtnAlterar, JBS_jBtnExcluir, JBS_jBtnPesquisar);
        Util.mensagem("Operação Cancelada");
        Util.limparCampos(JBS_jTxtCodigo, JBS_jTxtNome, JBS_jTxtApelido, JBS_jFmtCpf, JBS_jFmtDataNascimento, JBS_jPwfSenha,
            JBS_jCboNivel, JBS_jChbAtivo);
    }//GEN-LAST:event_JBS_jBtnCancelarActionPerformed

    private void JBS_jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBS_jTxtCodigoActionPerformed

    private void JBS_jCboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jCboNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBS_jCboNivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuario dialog = new JDlgUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBS_jBtnAlterar;
    private javax.swing.JButton JBS_jBtnCancelar;
    private javax.swing.JButton JBS_jBtnConfirmar;
    private javax.swing.JButton JBS_jBtnExcluir;
    private javax.swing.JButton JBS_jBtnIncluir;
    private javax.swing.JButton JBS_jBtnPesquisar;
    private javax.swing.JComboBox<String> JBS_jCboNivel;
    private javax.swing.JCheckBox JBS_jChbAtivo;
    private javax.swing.JFormattedTextField JBS_jFmtCpf;
    private javax.swing.JFormattedTextField JBS_jFmtDataNascimento;
    private javax.swing.JPasswordField JBS_jPwfSenha;
    private javax.swing.JTextField JBS_jTxtApelido;
    private javax.swing.JTextField JBS_jTxtCodigo;
    private javax.swing.JTextField JBS_jTxtNome;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
