/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.JbsVendedor;
import dao.VendedorDAO;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author Janaína B da Silva
 */
public class JDlgVendedorIA extends javax.swing.JDialog {

    VendedorDAO vendedorDAO;
    JDlgVendedor jDlgVendedor;
    JbsVendedor jbsVendedor;
    boolean incluir;
    Util util;
    MaskFormatter mascaraCelular;
    MaskFormatter mascaraCpf;
    MaskFormatter mascaraData;
    /**
     * Creates new form JDlgVendedor
     */
    public JDlgVendedorIA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        Limpar();
        incluir = false;
        vendedorDAO = new VendedorDAO();
        jbsVendedor = new JbsVendedor();
        
        try {
            mascaraCelular = new MaskFormatter("(##) #####-####");
            mascaraCpf = new MaskFormatter("###.###.###-##");
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgVendedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JBS_jFmtCelular.setFormatterFactory(new DefaultFormatterFactory(mascaraCelular));
        JBS_jFmtCPF.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
        JBS_jFmtDataNasc.setFormatterFactory(new DefaultFormatterFactory(mascaraData));
    }
    
    public void Limpar(){
        util.limparCampos(JBS_jFmtCPF, 
                JBS_jFmtCelular,
                JBS_jFmtDataNasc,
                JBS_jTxtCodigo,
                JBS_jTxtEmail,
                JBS_jTxtEstado,
                JBS_jTxtGenero,
                JBS_jTxtNome
        );
    }
    
    public JbsVendedor ViewBean(){
        JbsVendedor jbsVendedor = new JbsVendedor();
        int id = Integer.valueOf(JBS_jTxtCodigo.getText());
        jbsVendedor.setJbsIdVendedor(id);
        jbsVendedor.setJbsNome(JBS_jTxtNome.getText());
        jbsVendedor.setJbsEmail(JBS_jTxtEmail.getText());
        jbsVendedor.setJbsCelular(JBS_jFmtCelular.getText());
        jbsVendedor.setJbsCpf(JBS_jFmtCPF.getText());
        //vendedor.setData_Nasc(jFmtDataNasc.gteText());
        jbsVendedor.setJbsEstado(JBS_jTxtEstado.getText());
        jbsVendedor.setJbsGenero(JBS_jTxtGenero.getText());
        return jbsVendedor;
    }
    
    public void beanView(JbsVendedor jbsVendedor){
        String valor = String.valueOf(jbsVendedor.getJbsIdVendedor());
        JBS_jTxtCodigo.setText(valor);
        JBS_jTxtNome.setText(jbsVendedor.getJbsNome());
        JBS_jTxtEmail.setText(jbsVendedor.getJbsEmail());
        JBS_jFmtCelular.setText(jbsVendedor.getJbsCelular());
        JBS_jFmtCPF.setText(jbsVendedor.getJbsCpf());
//        jFmtDataNasc.setText(vendedor.getData_nasc());
        JBS_jTxtEstado.setText(jbsVendedor.getJbsEstado());
        JBS_jTxtGenero.setText(jbsVendedor.getJbsGenero());
    }
    
    public void TelaAnterior(JDlgVendedor jDlgVendedor){
        jDlgVendedor = jDlgVendedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBS_jTxtGenero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JBS_jTxtNome = new javax.swing.JTextField();
        JBS_jTxtCodigo = new javax.swing.JTextField();
        JBS_jTxtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JBS_jFmtCelular = new javax.swing.JFormattedTextField();
        JBS_jFmtCPF = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        JBS_jFmtDataNasc = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        JBS_jTxtEstado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JBS_jBtnOK = new javax.swing.JButton();
        JBS_jBtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("Genêro");

        jLabel4.setText("CPF");

        JBS_jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jTxtNomeActionPerformed(evt);
            }
        });

        JBS_jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jTxtCodigoActionPerformed(evt);
            }
        });

        jLabel8.setText("Codigo");

        jLabel1.setText("Nome");

        jLabel2.setText("Email");

        jLabel5.setText("Data de Nascimento");

        jLabel3.setText("Ceular");

        jLabel6.setText("Estado");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        JBS_jBtnOK.setText("Ok");
        JBS_jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jBtnOKActionPerformed(evt);
            }
        });
        jPanel1.add(JBS_jBtnOK);

        JBS_jBtnCancelar.setText("Cancelar");
        JBS_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jBtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(JBS_jBtnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JBS_jFmtCelular, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JBS_jTxtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JBS_jTxtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBS_jTxtEstado)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(JBS_jFmtDataNasc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JBS_jFmtCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(JBS_jTxtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(JBS_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(157, 157, 157))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBS_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBS_jFmtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBS_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBS_jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBS_jFmtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBS_jTxtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBS_jFmtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBS_jTxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBS_jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBS_jTxtCodigoActionPerformed

    private void JBS_jBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jBtnOKActionPerformed
        // TODO add your handling code here:
        if(getTitle().equals("Inclusão")){
            jbsVendedor = ViewBean();
            vendedorDAO.insert(jbsVendedor);
            util.mensagem("Incluindo");
            setVisible(false);
        }else if(getTitle().equals("Alteração")){
        vendedorDAO.update(jbsVendedor);
        util.mensagem("Alterando");
        JBS_jTxtCodigo.setEnabled(false);
        setVisible(false);
        } else{
            util.mensagem("ERRO");
        }
    }//GEN-LAST:event_JBS_jBtnOKActionPerformed

    private void JBS_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        util.mensagem("Você cancelou a operação");
        setVisible(false);
        Limpar();
    }//GEN-LAST:event_JBS_jBtnCancelarActionPerformed

    private void JBS_jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBS_jTxtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedorIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedorIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedorIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedorIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendedorIA dialog = new JDlgVendedorIA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBS_jBtnCancelar;
    private javax.swing.JButton JBS_jBtnOK;
    private javax.swing.JFormattedTextField JBS_jFmtCPF;
    private javax.swing.JFormattedTextField JBS_jFmtCelular;
    private javax.swing.JFormattedTextField JBS_jFmtDataNasc;
    private javax.swing.JTextField JBS_jTxtCodigo;
    private javax.swing.JTextField JBS_jTxtEmail;
    private javax.swing.JTextField JBS_jTxtEstado;
    private javax.swing.JTextField JBS_jTxtGenero;
    private javax.swing.JTextField JBS_jTxtNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
