/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.JbsProduto;
import bean.JbsVendaProduto;
import dao.ProdutoDAO;
import dao.VendasDAO;
import java.util.ArrayList;
import java.util.List;
import tools.Util;

/**
 *
 * @author Janaína B da Silva
 */
public class JDlgVendasProduto extends javax.swing.JDialog {

    private ProdutoDAO produtoDAO;
    JbsProduto jbsProduto;
    private VendasDAO vendasDAO;
    public JbsVendaProduto jbsVendaProduto;
    JDlgVendas jDlgVendas;
    VendasProdutoControle vendasProdutoControle;
    int IdVendaN;
    /**
     * Creates new form JDlgVendasProduto
     */
    public JDlgVendasProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cadastro de Vendas");
        Util.habilitar(false, JBS_jTxtTotal);
        jDlgVendas = new JDlgVendas(null, true);
        vendasDAO = new VendasDAO();
        List lista = new ArrayList();
        
        ProdutoDAO produtoDAO = new ProdutoDAO();
        List lista1 = produtoDAO.listAll();
        for (int p = 0; p < lista1.size(); p++) {
        JBS_jCboProduto.addItem((JbsProduto)lista1.get(p));
        }
    }
    
    
    public void setTelaAnterior(JDlgVendas jDlgVendas){
        this.jDlgVendas = jDlgVendas;
//        this.numVendaId = numVendaId;
    }
    
    public JbsVendaProduto beanView(JbsVendaProduto jbsVendaProduto) {
        JBS_jCboProduto.setSelectedItem(jbsVendaProduto.getJbsProduto());
        JBS_jTxtQuantidade.setText(Integer.toString(Util.strInt(jbsVendaProduto.getJbsQuantida())));
        JBS_jTxtVUnitario.setText(Double.toString(jbsVendaProduto.getJbsVUnitario()));
        //jTxtTotal.setText(Double.toString(vendasProdutos.calculaTotal()));
        return jbsVendaProduto;
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBS_jBtnOK = new javax.swing.JButton();
        JBS_jBtnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JBS_jCboProduto = new javax.swing.JComboBox<JbsProduto>();
        jLabel2 = new javax.swing.JLabel();
        JBS_jTxtQuantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JBS_jTxtVUnitario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JBS_jTxtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JBS_jBtnOK.setText("OK");
        JBS_jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jBtnOKActionPerformed(evt);
            }
        });

        JBS_jBtnCancelar.setText("Cancelar");
        JBS_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jBtnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Produto");

        jLabel2.setText("Quantidade");

        jLabel3.setText("Valor Unitário");

        JBS_jTxtVUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jTxtVUnitarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(JBS_jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(JBS_jTxtVUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JBS_jBtnOK)
                                    .addComponent(jLabel4))
                                .addGap(31, 31, 31)
                                .addComponent(JBS_jBtnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(JBS_jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(JBS_jCboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBS_jCboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBS_jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBS_jTxtVUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBS_jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBS_jBtnOK)
                    .addComponent(JBS_jBtnCancelar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBS_jBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jBtnOKActionPerformed
        // TODO add your handling code here:
        JbsVendaProduto jbsVendaProduto = new JbsVendaProduto();
        jbsVendaProduto.setJbsProduto((JbsProduto) JBS_jCboProduto.getSelectedItem() );
        jbsVendaProduto.setJbsQuantida(JBS_jTxtQuantidade.getText() );
        jbsVendaProduto.setJbsVUnitario(Util.strDouble(JBS_jTxtVUnitario.getText()));
        if (getTitle().toUpperCase().substring(0, 1).equals("I")) {
           jDlgVendas.vendasProdutoControle.addBean(jbsVendaProduto);
        } else {            
            jDlgVendas.vendasProdutoControle.updateBean(jDlgVendas.getSelectedRowProd(), jbsVendaProduto);
        }
        setVisible(false);
    }//GEN-LAST:event_JBS_jBtnOKActionPerformed

    private void JBS_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        JDlgVendasProduto.this.dispose();
    }//GEN-LAST:event_JBS_jBtnCancelarActionPerformed

        private void JBS_jTxtQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtQuantidadeKeyReleased
        // TODO add your handling code here:
        if (JBS_jTxtQuantidade.getText().isEmpty() == false) {
            double unitario = Util.strDouble(JBS_jTxtQuantidade.getText());
            double quantidade = Util.strInt(JBS_jTxtQuantidade.getText());
            JBS_jTxtTotal.setText(String.valueOf(quantidade * unitario));
        } else {
            JBS_jTxtTotal.setText("0");
        }
    }//GEN-LAST:event_jTxtQuantidadeKeyReleased

    private void jCboProdutosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboProdutosItemStateChanged
        // TODO add your handling code here:
        JBS_jTxtQuantidade.setText( "1" );
        JbsProduto jbsProdutos = (JbsProduto) JBS_jCboProduto.getSelectedItem();
        JBS_jTxtVUnitario.setText( Util.doubleStr( jbsProdutos.getJbsValor()));
        JBS_jTxtTotal.setText(JBS_jTxtVUnitario.getText());
    }//GEN-LAST:event_jCboProdutosItemStateChanged

    private void JBS_jTxtVUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jTxtVUnitarioActionPerformed
        // TODO add your handling code here:
        if (JBS_jTxtVUnitario.getText().isEmpty() == false) {
            double unitario = Util.strDouble(JBS_jTxtQuantidade.getText());
            double quantidade = Util.strInt(JBS_jTxtQuantidade.getText());
            JBS_jTxtTotal.setText(String.valueOf(quantidade * unitario));
        } else {
            JBS_jTxtTotal.setText("0");
        }
    }//GEN-LAST:event_JBS_jTxtVUnitarioActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendasProduto dialog = new JDlgVendasProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBS_jBtnCancelar;
    private javax.swing.JButton JBS_jBtnOK;
    private javax.swing.JComboBox<JbsProduto> JBS_jCboProduto;
    private javax.swing.JTextField JBS_jTxtQuantidade;
    private javax.swing.JTextField JBS_jTxtTotal;
    private javax.swing.JTextField JBS_jTxtVUnitario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
