/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import query.JDlgConsultaCliente;
import query.JDlgConsultaProduto;
import query.JDlgConsultaUsuario;
import query.JDlgConsultaVendasProduto;
import query.JDlgConsultaVendedor;
import view.JDlgUsuario;
import view.JDlgCliente;
import view.JDlgProduto;
import view.JDlgVendedor;


/**
 *
 * @author Janaina
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setTitle("Brechó das roupas");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        JBS_jBtnCliente2 = new javax.swing.JButton();
        JBS_jBtnProdutos2 = new javax.swing.JButton();
        JBS_jBtnSair2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuPrincipal = new javax.swing.JMenu();
        jMnuClientes = new javax.swing.JMenuItem();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMnuVendedor = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuMovimentos = new javax.swing.JMenu();
        jMnuVendas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        JBS_jMnuConProduto = new javax.swing.JMenuItem();
        JBS_jMnuConUsuario = new javax.swing.JMenuItem();
        JBS_jMnuConVendedor = new javax.swing.JMenuItem();
        JBS_jMnuConCliente = new javax.swing.JMenuItem();
        JBS_jMnuConVendProd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_sistema.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        JBS_jBtnCliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-jake-16.png"))); // NOI18N
        JBS_jBtnCliente2.setFocusable(false);
        JBS_jBtnCliente2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBS_jBtnCliente2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JBS_jBtnCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jBtnCliente2ActionPerformed(evt);
            }
        });
        jToolBar1.add(JBS_jBtnCliente2);

        JBS_jBtnProdutos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-produto-16.png"))); // NOI18N
        JBS_jBtnProdutos2.setFocusable(false);
        JBS_jBtnProdutos2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBS_jBtnProdutos2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JBS_jBtnProdutos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jBtnProdutos2ActionPerformed(evt);
            }
        });
        jToolBar1.add(JBS_jBtnProdutos2);

        JBS_jBtnSair2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-sair-20.png"))); // NOI18N
        JBS_jBtnSair2.setFocusable(false);
        JBS_jBtnSair2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBS_jBtnSair2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JBS_jBtnSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jBtnSair2ActionPerformed(evt);
            }
        });
        jToolBar1.add(JBS_jBtnSair2);

        jMnuPrincipal.setMnemonic('P');
        jMnuPrincipal.setText("Principal");

        jMnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-jake-16.png"))); // NOI18N
        jMnuClientes.setMnemonic('C');
        jMnuClientes.setText("Cliente");
        jMnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientesActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuClientes);

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-gestão-de-cliente-16.png"))); // NOI18N
        jMnuUsuarios.setMnemonic('U');
        jMnuUsuarios.setText("Usuários");
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuUsuarios);

        jMnuVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-fornecedor-16.png"))); // NOI18N
        jMnuVendedor.setText("Vendedor");
        jMnuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendedorActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuVendedor);

        jMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-produto-16.png"))); // NOI18N
        jMnuProdutos.setText("Produtos");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuProdutos);
        jMnuPrincipal.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-sair-20.png"))); // NOI18N
        jMnuSair.setMnemonic('S');
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuPrincipal.add(jMnuSair);

        jMenuBar1.add(jMnuPrincipal);

        jMnuMovimentos.setMnemonic('M');
        jMnuMovimentos.setText("Movimentos");

        jMnuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-caixa-registradora-antiga-16.png"))); // NOI18N
        jMnuVendas.setMnemonic('V');
        jMnuVendas.setText("Vendas");
        jMnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendasActionPerformed(evt);
            }
        });
        jMnuMovimentos.add(jMnuVendas);
        jMnuMovimentos.add(jSeparator2);

        jMenuBar1.add(jMnuMovimentos);

        jMenu1.setText("Consultas");

        JBS_jMnuConProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-produto-16.png"))); // NOI18N
        JBS_jMnuConProduto.setText("Produto");
        JBS_jMnuConProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jMnuConProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(JBS_jMnuConProduto);

        JBS_jMnuConUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-gestão-de-cliente-16.png"))); // NOI18N
        JBS_jMnuConUsuario.setText("Usuario");
        JBS_jMnuConUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jMnuConUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(JBS_jMnuConUsuario);

        JBS_jMnuConVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-fornecedor-16.png"))); // NOI18N
        JBS_jMnuConVendedor.setText("Vendedor");
        JBS_jMnuConVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jMnuConVendedorActionPerformed(evt);
            }
        });
        jMenu1.add(JBS_jMnuConVendedor);

        JBS_jMnuConCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-jake-16.png"))); // NOI18N
        JBS_jMnuConCliente.setText("Cliente");
        JBS_jMnuConCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jMnuConClienteActionPerformed(evt);
            }
        });
        jMenu1.add(JBS_jMnuConCliente);

        JBS_jMnuConVendProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-purchase-for-euro-16.png"))); // NOI18N
        JBS_jMnuConVendProd.setText("Vendas Produto");
        JBS_jMnuConVendProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBS_jMnuConVendProdActionPerformed(evt);
            }
        });
        jMenu1.add(JBS_jMnuConVendProd);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2045, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientesActionPerformed
        // TODO add your handling code here:
        JDlgCliente  jDlgCliente = new JDlgCliente(null, true);
        jDlgCliente.setVisible(true);
    }//GEN-LAST:event_jMnuClientesActionPerformed

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgUsuario  jDlgUsuario = new JDlgUsuario(null, true);
        jDlgUsuario.setVisible(true);
    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMnuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendedorActionPerformed
        // TODO add your handling code here:
        JDlgVendedor  jDlgVendedor = new JDlgVendedor(null, true);
        jDlgVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuVendedorActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        // TODO add your handling code here:
        JDlgProduto  jDlgProduto = new JDlgProduto(null, true);
        jDlgProduto.setVisible(true);
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendasActionPerformed
        // TODO add your handling code here:
        JDlgVendas  jDlgVendas = new JDlgVendas(null, true);
        jDlgVendas.setVisible(true);
    }//GEN-LAST:event_jMnuVendasActionPerformed

    private void JBS_jMnuConProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jMnuConProdutoActionPerformed
        // TODO add your handling code here:
        JDlgConsultaProduto  jDlgConsultaProduto = new JDlgConsultaProduto(null, true);
        jDlgConsultaProduto.setVisible(true);
    }//GEN-LAST:event_JBS_jMnuConProdutoActionPerformed

    private void JBS_jMnuConUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jMnuConUsuarioActionPerformed
        // TODO add your handling code here:
        JDlgConsultaUsuario  jDlgConsultaUsuario = new JDlgConsultaUsuario(null, true);
        jDlgConsultaUsuario.setVisible(true);
    }//GEN-LAST:event_JBS_jMnuConUsuarioActionPerformed

    private void JBS_jMnuConVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jMnuConVendedorActionPerformed
        // TODO add your handling code here:
        JDlgConsultaVendedor  jDlgConsultaVendedor = new JDlgConsultaVendedor(null, true);
        jDlgConsultaVendedor.setVisible(true);
    }//GEN-LAST:event_JBS_jMnuConVendedorActionPerformed

    private void JBS_jMnuConClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jMnuConClienteActionPerformed
        // TODO add your handling code here:
        JDlgConsultaCliente  jDlgConsultaCliente = new JDlgConsultaCliente(null, true);
        jDlgConsultaCliente.setVisible(true);
    }//GEN-LAST:event_JBS_jMnuConClienteActionPerformed

    private void JBS_jBtnSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jBtnSair2ActionPerformed
        // TODO add your handling code here:
                System.exit(0);

    }//GEN-LAST:event_JBS_jBtnSair2ActionPerformed

    private void JBS_jBtnProdutos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jBtnProdutos2ActionPerformed
        // TODO add your handling code here:
        JDlgProduto  jDlgProduto = new JDlgProduto(null, true);
        jDlgProduto.setVisible(true);
    }//GEN-LAST:event_JBS_jBtnProdutos2ActionPerformed

    private void JBS_jBtnCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jBtnCliente2ActionPerformed
        // TODO add your handling code here:
        JDlgCliente  jDlgCliente = new JDlgCliente(null, true);
        jDlgCliente.setVisible(true);
    }//GEN-LAST:event_JBS_jBtnCliente2ActionPerformed

    private void JBS_jMnuConVendProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBS_jMnuConVendProdActionPerformed
        // TODO add your handling code here:
        JDlgConsultaVendasProduto jDlgConVP = new JDlgConsultaVendasProduto(null, true);
        jDlgConVP.setVisible(true);
    }//GEN-LAST:event_JBS_jMnuConVendProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBS_jBtnCliente2;
    private javax.swing.JButton JBS_jBtnProdutos2;
    private javax.swing.JButton JBS_jBtnSair2;
    private javax.swing.JMenuItem JBS_jMnuConCliente;
    private javax.swing.JMenuItem JBS_jMnuConProduto;
    private javax.swing.JMenuItem JBS_jMnuConUsuario;
    private javax.swing.JMenuItem JBS_jMnuConVendProd;
    private javax.swing.JMenuItem JBS_jMnuConVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuClientes;
    private javax.swing.JMenu jMnuMovimentos;
    private javax.swing.JMenu jMnuPrincipal;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JMenuItem jMnuVendas;
    private javax.swing.JMenuItem jMnuVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
