package bean;
// Generated 05/09/2023 08:19:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendasProdutos generated by hbm2java
 */
@Entity
@Table(name="vendas_produtos"
    ,catalog="mpv_aluno"
)
public class VendasProdutos  implements java.io.Serializable {


     private String idvendasProdutos;
     private Produtos produtos;
     private Vendas vendas;
     private String quantidade;
     private double valorUnitario;

    public VendasProdutos() {
    }

    public VendasProdutos(Produtos produtos, Vendas vendas, String quantidade, double valorUnitario) {
       this.produtos = produtos;
       this.vendas = vendas;
       this.quantidade = quantidade;
       this.valorUnitario = valorUnitario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idvendas_produtos", unique=true, nullable=false)
    public String getIdvendasProdutos() {
        return this.idvendasProdutos;
    }
    
    public void setIdvendasProdutos(String idvendasProdutos) {
        this.idvendasProdutos = idvendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produtos")
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendas")
    public Vendas getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Vendas vendas) {
        this.vendas = vendas;
    }

    
    @Column(name="quantidade")
    public String getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(String quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="valorUnitario", precision=10)
    public double getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }




}


