package bean;
// Generated 05/09/2023 08:19:41 by Hibernate Tools 4.3.1


//import java.math.BigDecimal;
import java.util.Date;
//import java.util.HashSet;
//import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
//import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vendas generated by hbm2java
 */
@Entity
@Table(name="vendas"
    ,catalog="mpv_aluno"
)
public class Vendas  implements java.io.Serializable {


     private int idvendas;
     private Clientes clientes;
     private Vendedor vendedor;
     private Date data;
     private double total;
//     private Set vendasProdutoses = new HashSet(0);

    public Vendas() {
    }

	
    public Vendas(int idvendas) {
        this.idvendas = idvendas;
    }
    public Vendas(int idvendas, Clientes clientes, Vendedor vendedor, Date data, double total) {
       this.idvendas = idvendas;
       this.clientes = clientes;
       this.vendedor = vendedor;
       this.data = data;
       this.total = total;
//       this.vendasProdutoses = vendasProdutoses;
    }
   
     @Id 

    
    @Column(name="idvendas", unique=true, nullable=false)
    public int getIdvendas() {
        return this.idvendas;
    }
    
    public void setIdvendas(int idvendas) {
        this.idvendas = idvendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente")
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendedor")
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", length=10)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="total", precision=10)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="vendas")
//    public Set getVendasProdutoses() {
//        return this.vendasProdutoses;
//    }
//    
//    public void setVendasProdutoses(Set vendasProdutoses) {
//        this.vendasProdutoses = vendasProdutoses;
//    }




}


