package bean;
// Generated 12/09/2023 09:26:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JbsCliente generated by hbm2java
 */
@Entity
@Table(name="jbs_cliente"
    ,catalog="db_janaina_silva"
)
public class JbsCliente  implements java.io.Serializable {


     private int jbsIdCliente;
     private String jbsNome;
     private String jbsCpf;
     private String jbsRg;
     private Date jbsDataNasc;
     private String jbsCelular;
     private String jbsGenero;
     private String jbsEmail;
     private String jbsNaturalidade;
     private String jbsRua;
     private String jbsBairro;
     private String jbsNumcasa;
     private String jbsCidade;
     private String jbsEstado;
     private String jbsCep;
     //private Set jbsVendas = new HashSet(0);

    public JbsCliente() {
    }

	
    public JbsCliente(int jbsIdCliente, String jbsNome, String jbsCpf, String jbsRg, Date jbsDataNasc, String jbsCelular, String jbsGenero, String jbsEmail, String jbsNaturalidade, String jbsRua, String jbsBairro, String jbsNumcasa, String jbsCidade, String jbsEstado, String jbsCep) {
        this.jbsIdCliente = jbsIdCliente;
        this.jbsNome = jbsNome;
        this.jbsCpf = jbsCpf;
        this.jbsRg = jbsRg;
        this.jbsDataNasc = jbsDataNasc;
        this.jbsCelular = jbsCelular;
        this.jbsGenero = jbsGenero;
        this.jbsEmail = jbsEmail;
        this.jbsNaturalidade = jbsNaturalidade;
        this.jbsRua = jbsRua;
        this.jbsBairro = jbsBairro;
        this.jbsNumcasa = jbsNumcasa;
        this.jbsCidade = jbsCidade;
        this.jbsEstado = jbsEstado;
        this.jbsCep = jbsCep;
    }
    public JbsCliente(int jbsIdCliente, String jbsNome, String jbsCpf, String jbsRg, Date jbsDataNasc, String jbsCelular, String jbsGenero, String jbsEmail, String jbsNaturalidade, String jbsRua, String jbsBairro, String jbsNumcasa, String jbsCidade, String jbsEstado, String jbsCep, Set jbsVendas) {
       this.jbsIdCliente = jbsIdCliente;
       this.jbsNome = jbsNome;
       this.jbsCpf = jbsCpf;
       this.jbsRg = jbsRg;
       this.jbsDataNasc = jbsDataNasc;
       this.jbsCelular = jbsCelular;
       this.jbsGenero = jbsGenero;
       this.jbsEmail = jbsEmail;
       this.jbsNaturalidade = jbsNaturalidade;
       this.jbsRua = jbsRua;
       this.jbsBairro = jbsBairro;
       this.jbsNumcasa = jbsNumcasa;
       this.jbsCidade = jbsCidade;
       this.jbsEstado = jbsEstado;
       this.jbsCep = jbsCep;
       //this.jbsVendas = jbsVendas;
    }
   
     @Id 

    
    @Column(name="jbs_id_cliente", unique=true, nullable=false)
    public int getJbsIdCliente() {
        return this.jbsIdCliente;
    }
    
    public void setJbsIdCliente(int jbsIdCliente) {
        this.jbsIdCliente = jbsIdCliente;
    }

    
    @Column(name="jbs_nome", nullable=false, length=100)
    public String getJbsNome() {
        return this.jbsNome;
    }
    
    public void setJbsNome(String jbsNome) {
        this.jbsNome = jbsNome;
    }

    
    @Column(name="jbs_cpf", nullable=false, length=45)
    public String getJbsCpf() {
        return this.jbsCpf;
    }
    
    public void setJbsCpf(String jbsCpf) {
        this.jbsCpf = jbsCpf;
    }

    
    @Column(name="jbs_rg", nullable=false, length=45)
    public String getJbsRg() {
        return this.jbsRg;
    }
    
    public void setJbsRg(String jbsRg) {
        this.jbsRg = jbsRg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jbs_data_nasc", nullable=false, length=10)
    public Date getJbsDataNasc() {
        return this.jbsDataNasc;
    }
    
    public void setJbsDataNasc(Date jbsDataNasc) {
        this.jbsDataNasc = jbsDataNasc;
    }

    
    @Column(name="jbs_celular", nullable=false, length=15)
    public String getJbsCelular() {
        return this.jbsCelular;
    }
    
    public void setJbsCelular(String jbsCelular) {
        this.jbsCelular = jbsCelular;
    }

    
    @Column(name="jbs_genero", nullable=false, length=1)
    public String getJbsGenero() {
        return this.jbsGenero;
    }
    
    public void setJbsGenero(String jbsGenero) {
        this.jbsGenero = jbsGenero;
    }

    
    @Column(name="jbs_email", nullable=false, length=200)
    public String getJbsEmail() {
        return this.jbsEmail;
    }
    
    public void setJbsEmail(String jbsEmail) {
        this.jbsEmail = jbsEmail;
    }

    
    @Column(name="jbs_naturalidade", nullable=false, length=60)
    public String getJbsNaturalidade() {
        return this.jbsNaturalidade;
    }
    
    public void setJbsNaturalidade(String jbsNaturalidade) {
        this.jbsNaturalidade = jbsNaturalidade;
    }

    
    @Column(name="jbs_rua", nullable=false, length=100)
    public String getJbsRua() {
        return this.jbsRua;
    }
    
    public void setJbsRua(String jbsRua) {
        this.jbsRua = jbsRua;
    }

    
    @Column(name="jbs_bairro", nullable=false, length=100)
    public String getJbsBairro() {
        return this.jbsBairro;
    }
    
    public void setJbsBairro(String jbsBairro) {
        this.jbsBairro = jbsBairro;
    }

    
    @Column(name="jbs_numcasa", nullable=false, length=100)
    public String getJbsNumcasa() {
        return this.jbsNumcasa;
    }
    
    public void setJbsNumcasa(String jbsNumcasa) {
        this.jbsNumcasa = jbsNumcasa;
    }

    
    @Column(name="jbs_cidade", nullable=false, length=100)
    public String getJbsCidade() {
        return this.jbsCidade;
    }
    
    public void setJbsCidade(String jbsCidade) {
        this.jbsCidade = jbsCidade;
    }

    
    @Column(name="jbs_estado", nullable=false, length=2)
    public String getJbsEstado() {
        return this.jbsEstado;
    }
    
    public void setJbsEstado(String jbsEstado) {
        this.jbsEstado = jbsEstado;
    }

    
    @Column(name="jbs_cep", nullable=false, length=11)
    public String getJbsCep() {
        return this.jbsCep;
    }
    
    public void setJbsCep(String jbsCep) {
        this.jbsCep = jbsCep;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="jbsCliente")
//    public Set getJbsVendas() {
//        return this.jbsVendas;
//    }
//    
//    public void setJbsVendas(Set jbsVendas) {
//        this.jbsVendas = jbsVendas;
//    }




}


