package bean;
// Generated 30/10/2023 10:00:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JbsProduto generated by hbm2java
 */
@Entity
@Table(name="jbs_produto"
    ,catalog="db_janaina_silva"
)
public class JbsProduto  implements java.io.Serializable {


     private int jbsIdProduto;
     private String jbsNome;
     private double jbsValor;
     private int jbsCategoria;
     private String jbsEspecifica;
//     private Set pedidosProdutoses = new HashSet(0);
//     private Set jbsVendaProdutos = new HashSet(0);

    public JbsProduto() {
    }

	
    public JbsProduto(int jbsIdProduto, String jbsNome, double jbsValor, int jbsCategoria, String jbsEspecifica) {
        this.jbsIdProduto = jbsIdProduto;
        this.jbsNome = jbsNome;
        this.jbsValor = jbsValor;
        this.jbsCategoria = jbsCategoria;
        this.jbsEspecifica = jbsEspecifica;
    }
//    public JbsProduto(int jbsIdProduto, String jbsNome, BigDecimal jbsValor, String jbsCategoria, String jbsEspecifica, Set pedidosProdutoses, Set jbsVendaProdutos) {
//       this.jbsIdProduto = jbsIdProduto;
//       this.jbsNome = jbsNome;
//       this.jbsValor = jbsValor;
//       this.jbsCategoria = jbsCategoria;
//       this.jbsEspecifica = jbsEspecifica;
//       this.pedidosProdutoses = pedidosProdutoses;
//       this.jbsVendaProdutos = jbsVendaProdutos;
//    }
   
     @Id 

    
    @Column(name="jbs_id_produto", unique=true, nullable=false)
    public int getJbsIdProduto() {
        return this.jbsIdProduto;
    }
    
    public void setJbsIdProduto(int jbsIdProduto) {
        this.jbsIdProduto = jbsIdProduto;
    }

    
    @Column(name="jbs_nome", nullable=false, length=100)
    public String getJbsNome() {
        return this.jbsNome;
    }
    
    public void setJbsNome(String jbsNome) {
        this.jbsNome = jbsNome;
    }

    
    @Column(name="jbs_valor", nullable=false, precision=15)
    public double getJbsValor() {
        return this.jbsValor;
    }
    
    public void setJbsValor(double jbsValor) {
        this.jbsValor = jbsValor;
    }

    
    @Column(name="jbs_categoria", nullable=false)
    public int getJbsCategoria() {
        return this.jbsCategoria;
    }
    
    public void setJbsCategoria(int jbsCategoria) {
        this.jbsCategoria = jbsCategoria;
    }

    
    @Column(name="jbs_especifica", nullable=false, length=45)
    public String getJbsEspecifica() {
        return this.jbsEspecifica;
    }
    
    public void setJbsEspecifica(String jbsEspecifica) {
        this.jbsEspecifica = jbsEspecifica;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="jbsProduto")
//    public Set getPedidosProdutoses() {
//        return this.pedidosProdutoses;
//    }
//    
//    public void setPedidosProdutoses(Set pedidosProdutoses) {
//        this.pedidosProdutoses = pedidosProdutoses;
//    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="jbsProduto")
//    public Set getJbsVendaProdutos() {
//        return this.jbsVendaProdutos;
//    }
//    
//    public void setJbsVendaProdutos(Set jbsVendaProdutos) {
//        this.jbsVendaProdutos = jbsVendaProdutos;
//    }




}


