package bean;
// Generated 12/09/2023 09:26:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JbsUsuario generated by hbm2java
 */
@Entity
@Table(name="jbs_usuario"
    ,catalog="db_janaina_silva"
)
public class JbsUsuario  implements java.io.Serializable {


     private int jbsIdUsuario;
     private String jbsNome;
     private String jbsApelido;
     private String jbsCpf;
     private Date jbsDataNasc;
     private String jbsSenha;
     private int jbsNivel;
     private String jbsAtivo;

    public JbsUsuario() {
    }

    public JbsUsuario(int jbsIdUsuario, String jbsNome, String jbsApelido, String jbsCpf, Date jbsDataNasc, String jbsSenha, int jbsNivel, String jbsAtivo) {
       this.jbsIdUsuario = jbsIdUsuario;
       this.jbsNome = jbsNome;
       this.jbsApelido = jbsApelido;
       this.jbsCpf = jbsCpf;
       this.jbsDataNasc = jbsDataNasc;
       this.jbsSenha = jbsSenha;
       this.jbsNivel = jbsNivel;
       this.jbsAtivo = jbsAtivo;
    }
   
     @Id 

    
    @Column(name="jbs_id_usuario", unique=true, nullable=false)
    public int getJbsIdUsuario() {
        return this.jbsIdUsuario;
    }
    
    public void setJbsIdUsuario(int jbsIdUsuario) {
        this.jbsIdUsuario = jbsIdUsuario;
    }

    
    @Column(name="jbs_nome", nullable=false, length=100)
    public String getJbsNome() {
        return this.jbsNome;
    }
    
    public void setJbsNome(String jbsNome) {
        this.jbsNome = jbsNome;
    }

    
    @Column(name="jbs_apelido", nullable=false, length=40)
    public String getJbsApelido() {
        return this.jbsApelido;
    }
    
    public void setJbsApelido(String jbsApelido) {
        this.jbsApelido = jbsApelido;
    }

    
    @Column(name="jbs_cpf", nullable=false, length=45)
    public String getJbsCpf() {
        return this.jbsCpf;
    }
    
    public void setJbsCpf(String jbsCpf) {
        this.jbsCpf = jbsCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jbs_data_nasc", nullable=false, length=10)
    public Date getJbsDataNasc() {
        return this.jbsDataNasc;
    }
    
    public void setJbsDataNasc(Date jbsDataNasc) {
        this.jbsDataNasc = jbsDataNasc;
    }

    
    @Column(name="jbs_senha", nullable=false, length=20)
    public String getJbsSenha() {
        return this.jbsSenha;
    }
    
    public void setJbsSenha(String jbsSenha) {
        this.jbsSenha = jbsSenha;
    }

    
    @Column(name="jbs_nivel", nullable=false)
    public int getJbsNivel() {
        return this.jbsNivel;
    }
    
    public void setJbsNivel(int jbsNivel) {
        this.jbsNivel = jbsNivel;
    }

    
    @Column(name="jbs_ativo", nullable=false, length=1)
    public String getJbsAtivo() {
        return this.jbsAtivo;
    }
    
    public void setJbsAtivo(String jbsAtivo) {
        this.jbsAtivo = jbsAtivo;
    }

}


