package bean;
// Generated 08/12/2023 16:18:45 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JbsVenda generated by hbm2java
 */
@Entity
@Table(name="jbs_venda"
    ,catalog="db_janaina_silva"
)
public class JbsVenda  implements java.io.Serializable {


     private int jbsIdVenda;
     private JbsCliente jbsCliente;
     private JbsVendedor jbsVendedor;
     private Date jbsData;
     private double jbsTotal;
//     private Set jbsVendaProdutos = new HashSet(0);

    public JbsVenda() {
    }

	
    public JbsVenda(int jbsIdVenda, JbsCliente jbsCliente, JbsVendedor jbsVendedor, Date jbsData, double jbsTotal) {
        this.jbsIdVenda = jbsIdVenda;
        this.jbsCliente = jbsCliente;
        this.jbsVendedor = jbsVendedor;
        this.jbsData = jbsData;
        this.jbsTotal = jbsTotal;
    }
//    public JbsVenda(int jbsIdVenda, JbsCliente jbsCliente, JbsVendedor jbsVendedor, Date jbsData, BigDecimal jbsTotal, Set jbsVendaProdutos) {
//       this.jbsIdVenda = jbsIdVenda;
//       this.jbsCliente = jbsCliente;
//       this.jbsVendedor = jbsVendedor;
//       this.jbsData = jbsData;
//       this.jbsTotal = jbsTotal;
//       this.jbsVendaProdutos = jbsVendaProdutos;
//    }
   
     @Id 

    
    @Column(name="jbs_id_venda", unique=true, nullable=false)
    public int getJbsIdVenda() {
        return this.jbsIdVenda;
    }
    
    public void setJbsIdVenda(int jbsIdVenda) {
        this.jbsIdVenda = jbsIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jbs_cliente", nullable=false)
    public JbsCliente getJbsCliente() {
        return this.jbsCliente;
    }
    
    public void setJbsCliente(JbsCliente jbsCliente) {
        this.jbsCliente = jbsCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jbs_vendedor", nullable=false)
    public JbsVendedor getJbsVendedor() {
        return this.jbsVendedor;
    }
    
    public void setJbsVendedor(JbsVendedor jbsVendedor) {
        this.jbsVendedor = jbsVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jbs_data", nullable=false, length=10)
    public Date getJbsData() {
        return this.jbsData;
    }
    
    public void setJbsData(Date jbsData) {
        this.jbsData = jbsData;
    }

    
    @Column(name="jbs_total", nullable=false, precision=13)
    public double getJbsTotal() {
        return this.jbsTotal;
    }
    
    public void setJbsTotal(double jbsTotal) {
        this.jbsTotal = jbsTotal;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="jbsVenda")
//    public Set getJbsVendaProdutos() {
//        return this.jbsVendaProdutos;
//    }
//    
//    public void setJbsVendaProdutos(Set jbsVendaProdutos) {
//        this.jbsVendaProdutos = jbsVendaProdutos;
//    }




}


