package bean;
// Generated 30/10/2023 10:00:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name="pedidos"
    ,catalog="db_janaina_silva"
)
public class Pedidos  implements java.io.Serializable {


     private int idpedidos;
     private JbsCliente jbsCliente;
     private JbsVendedor jbsVendedor;
     private Date data;
     private double total;
//     private Set pedidosProdutoses = new HashSet(0);

    public Pedidos() {
    }

	
    public Pedidos(int idpedidos, JbsCliente jbsCliente, JbsVendedor jbsVendedor, Date data, double total) {
        this.idpedidos = idpedidos;
        this.jbsCliente = jbsCliente;
        this.jbsVendedor = jbsVendedor;
        this.data = data;
        this.total = total;
    }
//    public Pedidos(int idpedidos, JbsCliente jbsCliente, JbsVendedor jbsVendedor, Date data, BigDecimal total, Set pedidosProdutoses) {
//       this.idpedidos = idpedidos;
//       this.jbsCliente = jbsCliente;
//       this.jbsVendedor = jbsVendedor;
//       this.data = data;
//       this.total = total;
//       this.pedidosProdutoses = pedidosProdutoses;
//    }
   
     @Id 

    
    @Column(name="idpedidos", unique=true, nullable=false)
    public int getIdpedidos() {
        return this.idpedidos;
    }
    
    public void setIdpedidos(int idpedidos) {
        this.idpedidos = idpedidos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente", nullable=false)
    public JbsCliente getJbsCliente() {
        return this.jbsCliente;
    }
    
    public void setJbsCliente(JbsCliente jbsCliente) {
        this.jbsCliente = jbsCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendedor", nullable=false)
    public JbsVendedor getJbsVendedor() {
        return this.jbsVendedor;
    }
    
    public void setJbsVendedor(JbsVendedor jbsVendedor) {
        this.jbsVendedor = jbsVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", nullable=false, length=10)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="total", nullable=false, precision=10)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="pedidos")
//    public Set getPedidosProdutoses() {
//        return this.pedidosProdutoses;
//    }
//    
//    public void setPedidosProdutoses(Set pedidosProdutoses) {
//        this.pedidosProdutoses = pedidosProdutoses;
//    }




}


