package bean;
// Generated 30/10/2023 10:00:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PedidosProdutos generated by hbm2java
 */
@Entity
@Table(name="pedidos_produtos"
    ,catalog="db_janaina_silva"
)
public class PedidosProdutos  implements java.io.Serializable {


     private int idpedidosProdutos;
     private JbsProduto jbsProduto;
     private Pedidos pedidos;
     private int quantidade;
     private BigDecimal valorUnitario;

    public PedidosProdutos() {
    }

    public PedidosProdutos(int idpedidosProdutos, JbsProduto jbsProduto, Pedidos pedidos, int quantidade, BigDecimal valorUnitario) {
       this.idpedidosProdutos = idpedidosProdutos;
       this.jbsProduto = jbsProduto;
       this.pedidos = pedidos;
       this.quantidade = quantidade;
       this.valorUnitario = valorUnitario;
    }
   
     @Id 

    
    @Column(name="idpedidos_produtos", unique=true, nullable=false)
    public int getIdpedidosProdutos() {
        return this.idpedidosProdutos;
    }
    
    public void setIdpedidosProdutos(int idpedidosProdutos) {
        this.idpedidosProdutos = idpedidosProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produtos", nullable=false)
    public JbsProduto getJbsProduto() {
        return this.jbsProduto;
    }
    
    public void setJbsProduto(JbsProduto jbsProduto) {
        this.jbsProduto = jbsProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pedidos", nullable=false)
    public Pedidos getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Pedidos pedidos) {
        this.pedidos = pedidos;
    }

    
    @Column(name="quantidade", nullable=false)
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="valorUnitario", nullable=false, precision=10)
    public BigDecimal getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(BigDecimal valorUnitario) {
        this.valorUnitario = valorUnitario;
    }




}


